# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Auto < Formula
  desc "On-demand privileged debug pod CLI for EKS Auto Mode (Bottlerocket) nodes — tcpdump, journalctl, metrics, nsenter"
  homepage "https://github.com/viveksb007/autoscope"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/viveksb007/autoscope/releases/download/v1.0.0/auto_1.0.0_darwin_amd64.tar.gz"
      sha256 "c1518a10513cf37222eef7a5228f0a0de9cf47f69fc6947d44e65449d1f18f96"

      define_method(:install) do
        bin.install "auto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/viveksb007/autoscope/releases/download/v1.0.0/auto_1.0.0_darwin_arm64.tar.gz"
      sha256 "3abf81761fb568873e8be4f29a081b41757df2ef9740b00265853da7f6a7bdd8"

      define_method(:install) do
        bin.install "auto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/viveksb007/autoscope/releases/download/v1.0.0/auto_1.0.0_linux_amd64.tar.gz"
      sha256 "3542185c3fb38b063bdcf1ac30d3e5bcb50eab090e0f63c404b048d339951cbf"
      define_method(:install) do
        bin.install "auto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/viveksb007/autoscope/releases/download/v1.0.0/auto_1.0.0_linux_arm64.tar.gz"
      sha256 "76304fecc616375bf208f3bfec6c8e1ac7d1b645dc0509358da5cb24e8f9da21"
      define_method(:install) do
        bin.install "auto"
      end
    end
  end

  test do
    system "#{bin}/auto", "version"
  end
end
