# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bpftui < Formula
  desc "An interactive Terminal User Interface (TUI) for exploring BPF programs and maps"
  homepage "https://github.com/viveksb007/bpftui"
  version "0.1.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/viveksb007/bpftui/releases/download/v0.1.0/bpftui_0.1.0_linux_amd64.tar.gz"
    sha256 "a3388e8614d6517915e40c0fd42ccbdf47cc146bdc507769dd58e546244b38be"
    def install
      bin.install "bpftui"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/viveksb007/bpftui/releases/download/v0.1.0/bpftui_0.1.0_linux_arm64.tar.gz"
    sha256 "a4d1ad661e4f5a0ea1299c88caaa7b47457caf02a02945d3837dc1e4c0ad7727"
    def install
      bin.install "bpftui"
    end
  end

  test do
    system "#{bin}/bpftui", "--version"
  end
end
