# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoBore < Formula
  desc "A modern port forwarding tool written in Go"
  homepage "https://github.com/viveksb007/go-bore"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/viveksb007/go-bore/releases/download/v1.0.1/go-bore_1.0.1_darwin_amd64.tar.gz"
      sha256 "1202d49b69d7b1f251706cad0aef85320f96c08613560e6cc81f01f99b238077"

      def install
        bin.install "gobore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/viveksb007/go-bore/releases/download/v1.0.1/go-bore_1.0.1_darwin_arm64.tar.gz"
      sha256 "afe26767da3827228956b27469985aa92a6cfbcc87945e5f3773d736680b5e94"

      def install
        bin.install "gobore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/viveksb007/go-bore/releases/download/v1.0.1/go-bore_1.0.1_linux_amd64.tar.gz"
      sha256 "c0f52dbcda9b33fcc6339e44cb509e01d542e4dd61614c7fcbe56bfc16c50326"
      def install
        bin.install "gobore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/viveksb007/go-bore/releases/download/v1.0.1/go-bore_1.0.1_linux_arm64.tar.gz"
      sha256 "5fd61faca8f5177fd242250204dd35ed8464515c0e48e21861273aa7f0fbbb88"
      def install
        bin.install "gobore"
      end
    end
  end

  test do
    system "#{bin}/gobore", "--version"
  end
end
