# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gobore < Formula
  desc "A modern port forwarding tool written in Go"
  homepage "https://github.com/viveksb007/go-bore"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/viveksb007/go-bore/releases/download/v1.0.2/gobore_1.0.2_darwin_amd64.tar.gz"
      sha256 "ed4db800fd1ac35d7ab51f8dfcba1dc9826f5e1406a276c97b4375050f6473d4"

      def install
        bin.install "gobore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/viveksb007/go-bore/releases/download/v1.0.2/gobore_1.0.2_darwin_arm64.tar.gz"
      sha256 "e7f930c57f69c4cecc351e9f5f1c1ff4bf1f8faf305803d621c1d2427f43b1f6"

      def install
        bin.install "gobore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/viveksb007/go-bore/releases/download/v1.0.2/gobore_1.0.2_linux_amd64.tar.gz"
      sha256 "6f1a7d1498566850ef4260c0392d2158123b8d6f162b7dc073ccaf32dbf60ad8"
      def install
        bin.install "gobore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/viveksb007/go-bore/releases/download/v1.0.2/gobore_1.0.2_linux_arm64.tar.gz"
      sha256 "652aed608a0fe973bc23a4a05f6b39dcede5968c589f63f7572b1e6a26e7c83b"
      def install
        bin.install "gobore"
      end
    end
  end

  test do
    system "#{bin}/gobore", "--version"
  end
end
