# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gobpftool < Formula
  desc "A Go-based CLI tool for inspecting eBPF programs and maps"
  homepage "https://github.com/viveksb007/gobpftool"
  version "0.1.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/viveksb007/gobpftool/releases/download/v0.1.0/gobpftool_0.1.0_linux_amd64.tar.gz"
    sha256 "a0b568b898e06081e6cd795798511c10c655066cecc6b9070386ca6ad9302f87"
    def install
      bin.install "gobpftool"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/viveksb007/gobpftool/releases/download/v0.1.0/gobpftool_0.1.0_linux_arm64.tar.gz"
    sha256 "9f6b019f8b8f8e348989095e9c847bb699a4f00f7abf4c6d58c45907b4e3c560"
    def install
      bin.install "gobpftool"
    end
  end

  test do
    system "#{bin}/gobpftool", "--version"
  end
end
